### ISSUE TITLE
I can't bootstrap the application

### ISSUE THREAD

**Issue by CommanderXL** [tojoNozomi/iss-autofetch#1]
After I download the code and install superagent and cheerio.

the run run.bat.  It display nothing in mac.

**Comment by tojoNozomi** [comment]
I‘m so sorry that this scripts just for windows.I have no mac devices.I would edit the doc.Thanks you!

**Comment by CommanderXL** [comment]
好吧。那我还是用window试试


原始邮件
发件人:tojoNozominotifications@github.com
收件人:tojoNozomi/iss-autofetchiss-autofetch@noreply.github.com
抄送:XRene1017653702@qq.com
发送时间:2016年3月16日(周三) 11:04
主题:Re: [iss-autofetch] I can't bootstrap the application (#1)


I‘m so sorry that this scripts just for windows.I have no mac devices.I would edit the doc.Thanks you!

**Comment by tojoNozomi** [comment]
最近这个网站也是有点容易抽风，你也可以尝试去写一下mac版的嘛。我有同学写过一个不过我没收藏起来。
